[build-system]
requires = ["setuptools>=75.0", "setuptools_scm[toml]"]
build-backend = "setuptools.build_meta"

[project]
name = "bax_algorithms"
description = "Collection of algorithms that can be used in Bayesian Algorithm Execution (BAX) Xopt generators."
readme = "README.md"
authors = [
  { name = "SLAC National Accelerator Laboratory"},
]
keywords = ["machine learning", "accelerator physics"]
classifiers = [
    "Natural Language :: English",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3.13",
    "Intended Audience :: Science/Research",
    "Topic :: Scientific/Engineering",
]
requires-python = ">=3.10"
dependencies = [
    "numpy",
    "botorch>=0.8.5",
    "gpytorch>=1.10",
    "pydantic>=1.10.9",
    "scipy>=1.10.1",
    "xopt>=2.6.11",
    "jupyterlab>=3",
]
dynamic = ["version"]
[tool.setuptools_scm]
version_file = "bax_algorithms/_version.py"

[project.optional-dependencies]
dev = [
    "pytest"
]

[project.urls]
Homepage = "https://github.com/xopt-org/bax_algorithms"

[project.license]
file = "LICENSE"

[options]
zip_safe = false
include_package_data = true

[tool.setuptools.packages.find]
include = [ "bax_algorithms", ]
namespaces = false
